# -*- coding: utf-8 -*-
# pylint: disable=line-too-long
#
# This file is part of Lalf.
#
# Lalf is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Lalf is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Lalf.  If not, see <http://www.gnu.org/licenses/>.

"""
Module defining some phpbb-related constants
"""

from collections import OrderedDict

BBCODES = [
    {"bbcode_tag" : 'strike',
     "bbcode_helpline" : 'Texte barré',
     "display_on_posting" : 0,
     "bbcode_match" : '[strike]{TEXT}[/strike]',
     "bbcode_tpl" : '<span style=\"text-decoration: line-through;\">{TEXT}</span>',
     "first_pass_match" : '!\\[strike\\](.*?)\\[/strike\\]!ies',
     "first_pass_replace" : '\'[strike:$uid]\'.str_replace(array(\"\\r\\n\", \'\\\"\', \'\\\'\', \'(\', \')\'), array(\"\\n\", \'\"\', \'&#39;\', \'&#40;\', \'&#41;\'), trim(\'${1}\')).\'[/strike:$uid]\'',
     "second_pass_match" : '!\\[strike:$uid\\](.*?)\\[/strike:$uid\\]!s',
     "second_pass_replace" : '<span style=\"text-decoration: line-through;\">${1}</span>'},

    {"bbcode_tag" : 'left',
     "bbcode_helpline" : 'Texte aligné à gauche',
     "display_on_posting" : 0,
     "bbcode_match" : '[left]{TEXT}[/left]',
     "bbcode_tpl" : '<div style=\"text-align: left;\">{TEXT}</div>',
     "first_pass_match" : '!\\[left\\](.*?)\\[/left\\]!ies',
     "first_pass_replace" : '\'[left:$uid]\'.str_replace(array(\"\\r\\n\", \'\\\"\', \'\\\'\', \'(\', \')\'), array(\"\\n\", \'\"\', \'&#39;\', \'&#40;\', \'&#41;\'), trim(\'${1}\')).\'[/left:$uid]\'',
     "second_pass_match" : '!\\[left:$uid\\](.*?)\\[/left:$uid\\]!s',
     "second_pass_replace" : '<div style=\"text-align: left;\">${1}</div>'},

    {"bbcode_tag" : 'center',
     "bbcode_helpline" : 'Texte aligné au centre',
     "display_on_posting" : 0,
     "bbcode_match" : '[center]{TEXT}[/center]',
     "bbcode_tpl" : '<div style=\"text-align: center;\">{TEXT}</div>',
     "first_pass_match" : '!\\[center\\](.*?)\\[/center\\]!ies',
     "first_pass_replace" : '\'[center:$uid]\'.str_replace(array(\"\\r\\n\", \'\\\"\', \'\\\'\', \'(\', \')\'), array(\"\\n\", \'\"\', \'&#39;\', \'&#40;\', \'&#41;\'), trim(\'${1}\')).\'[/center:$uid]\'',
     "second_pass_match" : '!\\[center:$uid\\](.*?)\\[/center:$uid\\]!s',
     "second_pass_replace" : '<div style=\"text-align: center;\">${1}</div>'},

    {"bbcode_tag" : 'right',
     "bbcode_helpline" : 'Texte aligné à droite',
     "display_on_posting" : 0,
     "bbcode_match" : '[right]{TEXT}[/right]',
     "bbcode_tpl" : '<div style=\"text-align: right;\">{TEXT}</div>',
     "first_pass_match" : '!\\[right\\](.*?)\\[/right\\]!ies',
     "first_pass_replace" : '\'[right:$uid]\'.str_replace(array(\"\\r\\n\", \'\\\"\', \'\\\'\', \'(\', \')\'), array(\"\\n\", \'\"\', \'&#39;\', \'&#40;\', \'&#41;\'), trim(\'${1}\')).\'[/right:$uid]\'',
     "second_pass_match" : '!\\[right:$uid\\](.*?)\\[/right:$uid\\]!s',
     "second_pass_replace" : '<div style=\"text-align: right;\">${1}</div>'},

    {"bbcode_tag" : 'justify',
     "bbcode_helpline" : 'Texte justifié',
     "display_on_posting" : 0,
     "bbcode_match" : '[justify]{TEXT}[/justify]',
     "bbcode_tpl" : '<div style=\"text-align: justify;\">{TEXT}</div>',
     "first_pass_match" : '!\\[justify\\](.*?)\\[/justify\\]!ies',
     "first_pass_replace" : '\'[justify:$uid]\'.str_replace(array(\"\\r\\n\", \'\\\"\', \'\\\'\', \'(\', \')\'), array(\"\\n\", \'\"\', \'&#39;\', \'&#40;\', \'&#41;\'), trim(\'${1}\')).\'[/justify:$uid]\'',
     "second_pass_match" : '!\\[justify:$uid\\](.*?)\\[/justify:$uid\\]!s',
     "second_pass_replace" : '<div style=\"text-align: justify;\">${1}</div>'},

    {"bbcode_tag" : 'font=',
     "bbcode_helpline" : 'Modifier la police',
     "display_on_posting" : 0,
     "bbcode_match" : '[font={SIMPLETEXT}]{TEXT}[/font]',
     "bbcode_tpl" : '<span style=\"font-family: {SIMPLETEXT};\">{TEXT}</span>',
     "first_pass_match" : '!\\[font\\=([a-zA-Z0-9-+.,_ ]+)\\](.*?)\\[/font\\]!ies',
     "first_pass_replace" : '\'[font=${1}:$uid]\'.str_replace(array(\"\\r\\n\", \'\\\"\', \'\\\'\', \'(\', \')\'), array(\"\\n\", \'\"\', \'&#39;\', \'&#40;\', \'&#41;\'), trim(\'${2}\')).\'[/font:$uid]\'',
     "second_pass_match" : '!\\[font\\=([a-zA-Z0-9-+.,_ ]+):$uid\\](.*?)\\[/font:$uid\\]!s',
     "second_pass_replace" : '<span style=\"font-family: ${1};\">${2}</span>'},

    {"bbcode_tag" : 'table',
     "bbcode_helpline" : 'Tableau',
     "display_on_posting" : 0,
     "bbcode_match" : '[table]{TEXT}[/table]',
     "bbcode_tpl" : '<table>{TEXT}</table>',
     "first_pass_match" : '!\\[table\\](.*?)\\[/table\\]!ies',
     "first_pass_replace" : '\'[table:$uid]\'.str_replace(array(\"\\r\\n\", \'\\\"\', \'\\\'\', \'(\', \')\'), array(\"\\n\", \'\"\', \'&#39;\', \'&#40;\', \'&#41;\'), trim(\'${1}\')).\'[/table:$uid]\'',
     "second_pass_match" : '!\\[table:$uid\\](.*?)\\[/table:$uid\\]!s',
     "second_pass_replace" : '<table>${1}</table>'},

    {"bbcode_tag" : 'tr',
     "bbcode_helpline" : 'Ligne de tableau',
     "display_on_posting" : 0,
     "bbcode_match" : '[tr]{TEXT}[/tr]',
     "bbcode_tpl" : '<tr>{TEXT}</tr>',
     "first_pass_match" : '!\\[tr\\](.*?)\\[/tr\\]!ies',
     "first_pass_replace" : '\'[tr:$uid]\'.str_replace(array(\"\\r\\n\", \'\\\"\', \'\\\'\', \'(\', \')\'), array(\"\\n\", \'\"\', \'&#39;\', \'&#40;\', \'&#41;\'), trim(\'${1}\')).\'[/tr:$uid]\'',
     "second_pass_match" : '!\\[tr:$uid\\](.*?)\\[/tr:$uid\\]!s',
     "second_pass_replace" : '<tr>${1}</tr>'},

    {"bbcode_tag" : 'td',
     "bbcode_helpline" : 'Cellule de tableau',
     "display_on_posting" : 0,
     "bbcode_match" : '[td]{TEXT}[/td]',
     "bbcode_tpl" : '<td>{TEXT}</td>',
     "first_pass_match" : '!\\[td\\](.*?)\\[/td\\]!ies',
     "first_pass_replace" : '\'[td:$uid]\'.str_replace(array(\"\\r\\n\", \'\\\"\', \'\\\'\', \'(\', \')\'), array(\"\\n\", \'\"\', \'&#39;\', \'&#40;\', \'&#41;\'), trim(\'${1}\')).\'[/td:$uid]\'',
     "second_pass_match" : '!\\[td:$uid\\](.*?)\\[/td:$uid\\]!s',
     "second_pass_replace" : '<td>${1}</td>'},

    {"bbcode_tag" : 'td=',
     "bbcode_helpline" : '',
     "display_on_posting" : 0,
     "bbcode_match" : '[td={NUMBER1},{NUMBER2}]{TEXT}[/td]',
     "bbcode_tpl" : '<td colspan=\"{NUMBER1}\" rowspan=\"{NUMBER2}\">{TEXT}</td>',
     "first_pass_match" : '!\\[td\\=([0-9]+),([0-9]+)\\](.*?)\\[/td\\]!ies',
     "first_pass_replace" : '\'[td=${1},${2}:$uid]\'.str_replace(array(\"\\r\\n\", \'\\\"\', \'\\\'\', \'(\', \')\'), array(\"\\n\", \'\"\', \'&#39;\', \'&#40;\', \'&#41;\'), trim(\'${3}\')).\'[/td:$uid]\'',
     "second_pass_match" : '!\\[td\\=([0-9]+),([0-9]+):$uid\\](.*?)\\[/td:$uid\\]!s',
     "second_pass_replace" : '<td colspan=\"${1}\" rowspan=\"${2}\">${3}</td>'},

    {"bbcode_tag" : 'updown',
     "bbcode_helpline" : 'Texte défilant verticalement',
     "display_on_posting" : 0,
     "bbcode_match" : '[updown]{TEXT}[/updown]',
     "bbcode_tpl" : '<marquee height=\"60\" scrollamount=\"1\" direction=\"up\" behavior=\"scroll\">{TEXT}</marquee>',
     "first_pass_match" : '!\\[updown\\](.*?)\\[/updown\\]!ies',
     "first_pass_replace" : '\'[updown:$uid]\'.str_replace(array(\"\\r\\n\", \'\\\"\', \'\\\'\', \'(\', \')\'), array(\"\\n\", \'\"\', \'&#39;\', \'&#40;\', \'&#41;\'), trim(\'${1}\')).\'[/updown:$uid]\'',
     "second_pass_match" : '!\\[updown:$uid\\](.*?)\\[/updown:$uid\\]!s',
     "second_pass_replace" : '<marquee height=\"60\" scrollamount=\"1\" direction=\"up\" behavior=\"scroll\">${1}</marquee>'},

    {"bbcode_tag" : 'hr',
     "bbcode_helpline" : 'Ligne horizontale',
     "display_on_posting" : 0,
     "bbcode_match" : '[hr][/hr]',
     "bbcode_tpl" : '<hr />',
     "first_pass_match" : '!\\[hr\\]\\[/hr\\]!i',
     "first_pass_replace" : '[hr:$uid][/hr:$uid]',
     "second_pass_match" : '[hr:$uid][/hr:$uid]',
     "second_pass_replace" : ''},

    {"bbcode_tag" : 'scroll',
     "bbcode_helpline" : 'Texte défilant horizontalement',
     "display_on_posting" : 0,
     "bbcode_match" : '[scroll]{TEXT}[/scroll]',
     "bbcode_tpl" : '<marquee>{TEXT}</marquee>',
     "first_pass_match" : '!\\[scroll\\](.*?)\\[/scroll\\]!ies',
     "first_pass_replace" : '\'[scroll:$uid]\'.str_replace(array(\"\\r\\n\", \'\\\"\', \'\\\'\', \'(\', \')\'), array(\"\\n\", \'\"\', \'&#39;\', \'&#40;\', \'&#41;\'), trim(\'${1}\')).\'[/scroll:$uid]\'',
     "second_pass_match" : '!\\[scroll:$uid\\](.*?)\\[/scroll:$uid\\]!s',
     "second_pass_replace" : '<marquee>${1}</marquee>'},

    {"bbcode_tag" : 'sup',
     "bbcode_helpline" : 'Texte en exposant',
     "display_on_posting" : 0,
     "bbcode_match" : '[sup]{TEXT}[/sup]',
     "bbcode_tpl" : '<sup>{TEXT}</sup>',
     "first_pass_match" : '!\\[sup\\](.*?)\\[/sup\\]!ies',
     "first_pass_replace" : '\'[sup:$uid]\'.str_replace(array(\"\\r\\n\", \'\\\"\', \'\\\'\', \'(\', \')\'), array(\"\\n\", \'\"\', \'&#39;\', \'&#40;\', \'&#41;\'), trim(\'${1}\')).\'[/sup:$uid]\'',
     "second_pass_match" : '!\\[sup:$uid\\](.*?)\\[/sup:$uid\\]!s',
     "second_pass_replace" : '<sup>${1}</sup>'},

    {"bbcode_tag" : 'sub',
     "bbcode_helpline" : 'Texte en indice',
     "display_on_posting" : 0,
     "bbcode_match" : '[sub]{TEXT}[/sub]',
     "bbcode_tpl" : '<sub>{TEXT}</sub>',
     "first_pass_match" : '!\\[sub\\](.*?)\\[/sub\\]!ies',
     "first_pass_replace" : '\'[sub:$uid]\'.str_replace(array(\"\\r\\n\", \'\\\"\', \'\\\'\', \'(\', \')\'), array(\"\\n\", \'\"\', \'&#39;\', \'&#40;\', \'&#41;\'), trim(\'${1}\')).\'[/sub:$uid]\'',
     "second_pass_match" : '!\\[sub:$uid\\](.*?)\\[/sub:$uid\\]!s',
     "second_pass_replace" : '<sub>${1}</sub>'},

    {"bbcode_tag" : 'spoiler',
     "bbcode_helpline" : 'Spoiler',
     "display_on_posting" : 0,
     "bbcode_match" : '[spoiler]{TEXT}[/spoiler]',
     "bbcode_tpl" : '<dl class=\"codebox\"><dt>Spoiler: <a href=\"#\" onclick=\"var content = this.parentNode.parentNode.getElementsByTagName(\'dd\')[0]; if (content.style.display != \'\') { content.style.display = \'\'; this.innerText = \'Cacher\'; this.value = \'Hide\'; } else { content.style.display = \'none\'; this.innerText = \'Afficher\'; }; return false;\">Afficher</a></dt><dd style=\"display: none;\">{TEXT}</dd></dl>',
     "first_pass_match" : '!\\[spoiler\\](.*?)\\[/spoiler\\]!ies',
     "first_pass_replace" : '\'[spoiler:$uid]\'.str_replace(array(\"\\r\\n\", \'\\\"\', \'\\\'\', \'(\', \')\'), array(\"\\n\", \'\"\', \'&#39;\', \'&#40;\', \'&#41;\'), trim(\'${1}\')).\'[/spoiler:$uid]\'',
     "second_pass_match" : '!\\[spoiler:$uid\\](.*?)\\[/spoiler:$uid\\]!s',
     "second_pass_replace" : '<dl class=\"codebox\"><dt>Spoiler: <a href=\"#\" onclick=\"var content = this.parentNode.parentNode.getElementsByTagName(\'dd\')[0]; if (content.style.display != \'\') { content.style.display = \'\'; this.innerText = \'Cacher\'; this.value = \'Hide\'; } else { content.style.display = \'none\'; this.innerText = \'Afficher\'; }; return false;\">Afficher</a></dt><dd style=\"display: none;\">${1}</dd></dl>'},
]

for bbcode_id, bbcode in enumerate(BBCODES, 13):
    bbcode["bbcode_id"] = bbcode_id

BOTS = [
    {'name': 'AdsBot [Google]',
     'agent': 'AdsBot-Google'},
    {'name': 'Alexa [Bot]',
     'agent': 'ia_archiver'},
    {'name': 'Alta Vista [Bot]',
     'agent': 'Scooter/'},
    {'name': 'Ask Jeeves [Bot]',
     'agent': 'Ask Jeeves'},
    {'name': 'Baidu [Spider]',
     'agent': 'Baiduspider+('},
    {'name': 'Bing [Bot]',
     'agent': 'bingbot/'},
    {'name': 'Exabot [Bot]',
     'agent': 'Exabot/'},
    {'name': 'FAST Enterprise [Crawler]',
     'agent': 'FAST Enterprise Crawler'},
    {'name': 'FAST WebCrawler [Crawler]',
     'agent': 'FAST-WebCrawler/'},
    {'name': 'Francis [Bot]',
     'agent': 'http://www.neomo.de/'},
    {'name': 'Gigabot [Bot]',
     'agent': 'Gigabot/'},
    {'name': 'Google Adsense [Bot]',
     'agent': 'Mediapartners-Google'},
    {'name': 'Google Desktop',
     'agent': 'Google Desktop'},
    {'name': 'Google Feedfetcher',
     'agent': 'Feedfetcher-Google'},
    {'name': 'Google [Bot]',
     'agent': 'Googlebot'},
    {'name': 'Heise IT-Markt [Crawler]',
     'agent': 'heise-IT-Markt-Crawler'},
    {'name': 'Heritrix [Crawler]',
     'agent': 'heritrix/1.'},
    {'name': 'IBM Research [Bot]',
     'agent': 'ibm.com/cs/crawler'},
    {'name': 'ICCrawler - ICjobs',
     'agent': 'ICCrawler - ICjobs'},
    {'name': 'ichiro [Crawler]',
     'agent': 'ichiro/'},
    {'name': 'Majestic-12 [Bot]',
     'agent': 'MJ12bot/'},
    {'name': 'Metager [Bot]',
     'agent': 'MetagerBot/'},
    {'name': 'MSN NewsBlogs',
     'agent': 'msnbot-NewsBlogs/'},
    {'name': 'MSN [Bot]',
     'agent': 'msnbot/'},
    {'name': 'MSNbot Media',
     'agent': 'msnbot-media/'},
    {'name': 'NG-Search [Bot]',
     'agent': 'NG-Search/'},
    {'name': 'Nutch [Bot]',
     'agent': 'http://lucene.apache.org/nutch/'},
    {'name': 'Nutch/CVS [Bot]',
     'agent': 'NutchCVS/'},
    {'name': 'OmniExplorer [Bot]',
     'agent': 'OmniExplorer_Bot/'},
    {'name': 'Online link [Validator]',
     'agent': 'online link validator'},
    {'name': 'psbot [Picsearch]',
     'agent': 'psbot/0'},
    {'name': 'Seekport [Bot]',
     'agent': 'Seekbot/'},
    {'name': 'Sensis [Crawler]',
     'agent': 'Sensis Web Crawler'},
    {'name': 'SEO Crawler',
     'agent': 'SEO search Crawler/'},
    {'name': 'Seoma [Crawler]',
     'agent': 'Seoma [SEO Crawler]'},
    {'name': 'SEOSearch [Crawler]',
     'agent': 'SEOsearch/'},
    {'name': 'Snappy [Bot]',
     'agent': 'Snappy/1.1 ( http://www.urltrends.com/ )'},
    {'name': 'Steeler [Crawler]',
     'agent': 'http://www.tkl.iis.u-tokyo.ac.jp/~crawler/'},
    {'name': 'Synoo [Bot]',
     'agent': 'SynooBot/'},
    {'name': 'Telekom [Bot]',
     'agent': 'crawleradmin.t-info@telekom.de'},
    {'name': 'TurnitinBot [Bot]',
     'agent': 'TurnitinBot/'},
    {'name': 'Voyager [Bot]',
     'agent': 'voyager/1.0'},
    {'name': 'W3 [Sitesearch]',
     'agent': 'W3 SiteSearch Crawler'},
    {'name': 'W3C [Linkcheck]',
     'agent': 'W3C-checklink/'},
    {'name': 'W3C [Validator]',
     'agent': 'W3C_*Validator'},
    {'name': 'WiseNut [Bot]',
     'agent': 'http://www.WISEnutbot.com'},
    {'name': 'YaCy [Bot]',
     'agent': 'yacybot'},
    {'name': 'Yahoo MMCrawler [Bot]',
     'agent': 'Yahoo-MMCrawler/'},
    {'name': 'Yahoo Slurp [Bot]',
     'agent': 'Yahoo! DE Slurp'},
    {'name': 'Yahoo [Bot]',
     'agent': 'Yahoo! Slurp'},
    {'name': 'YahooSeeker [Bot]',
     'agent': 'YahooSeeker/'}]

SMILIES = OrderedDict((smiley["code"], smiley) for smiley in [
    {"code" : ":D",
     "emotion" : "Very Happy",
     "smiley_url" : "icon_e_biggrin.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ":-D",
     "emotion" : "Very Happy",
     "smiley_url" : "icon_e_biggrin.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ":grin:",
     "emotion" : "Very Happy",
     "smiley_url" : "icon_e_biggrin.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ":)",
     "emotion" : "Smile",
     "smiley_url" : "icon_e_smile.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ":-)",
     "emotion" : "Smile",
     "smiley_url" : "icon_e_smile.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ":smile:",
     "emotion" : "Smile",
     "smiley_url" : "icon_e_smile.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ";)",
     "emotion" : "Wink",
     "smiley_url" : "icon_e_wink.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ";-)",
     "emotion" : "Wink",
     "smiley_url" : "icon_e_wink.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ":wink:",
     "emotion" : "Wink",
     "smiley_url" : "icon_e_wink.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ":(",
     "emotion" : "Sad",
     "smiley_url" : "icon_e_sad.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ":-(",
     "emotion" : "Sad",
     "smiley_url" : "icon_e_sad.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ":sad:",
     "emotion" : "Sad",
     "smiley_url" : "icon_e_sad.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ":o",
     "emotion" : "Surprised",
     "smiley_url" : "icon_e_surprised.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ":-o",
     "emotion" : "Surprised",
     "smiley_url" : "icon_e_surprised.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ":eek:",
     "emotion" : "Surprised",
     "smiley_url" : "icon_e_surprised.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ":shock:",
     "emotion" : "Shocked",
     "smiley_url" : "icon_eek.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ":?",
     "emotion" : "Confused",
     "smiley_url" : "icon_e_confused.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ":-?",
     "emotion" : "Confused",
     "smiley_url" : "icon_e_confused.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ":???:",
     "emotion" : "Confused",
     "smiley_url" : "icon_e_confused.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : "8-)",
     "emotion" : "Cool",
     "smiley_url" : "icon_cool.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : "8)",
     "emotion" : "Cool",
     "smiley_url" : "icon_cool.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ":cool:",
     "emotion" : "Cool",
     "smiley_url" : "icon_cool.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ":lol:",
     "emotion" : "Laughing",
     "smiley_url" : "icon_lol.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ":x",
     "emotion" : "Mad",
     "smiley_url" : "icon_mad.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ":-x",
     "emotion" : "Mad",
     "smiley_url" : "icon_mad.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ":mad:",
     "emotion" : "Mad",
     "smiley_url" : "icon_mad.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ":P",
     "emotion" : "Razz",
     "smiley_url" : "icon_razz.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ":-P",
     "emotion" : "Razz",
     "smiley_url" : "icon_razz.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ":razz:",
     "emotion" : "Razz",
     "smiley_url" : "icon_razz.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ":oops:",
     "emotion" : "Embarrassed",
     "smiley_url" : "icon_redface.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ":cry:",
     "emotion" : "Crying or Very Sad",
     "smiley_url" : "icon_cry.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ":evil:",
     "emotion" : "Evil or Very Mad",
     "smiley_url" : "icon_evil.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ":twisted:",
     "emotion" : "Twisted Evil",
     "smiley_url" : "icon_twisted.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ":roll:",
     "emotion" : "Rolling Eyes",
     "smiley_url" : "icon_rolleyes.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ":!:",
     "emotion" : "Exclamation",
     "smiley_url" : "icon_exclaim.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ":?:",
     "emotion" : "Question",
     "smiley_url" : "icon_question.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ":idea:",
     "emotion" : "Idea",
     "smiley_url" : "icon_idea.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ":arrow:",
     "emotion" : "Arrow",
     "smiley_url" : "icon_arrow.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ":|",
     "emotion" : "Neutral",
     "smiley_url" : "icon_neutral.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ":-|",
     "emotion" : "Neutral",
     "smiley_url" : "icon_neutral.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ":mrgreen:",
     "emotion" : "Mr. Green",
     "smiley_url" : "icon_mrgreen.gif",
     "smiley_width" : 15,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ":geek:",
     "emotion" : "Geek",
     "smiley_url" : "icon_e_geek.gif",
     "smiley_width" : 17,
     "smiley_height" : 17,
     "display_on_posting" : 1},
    {"code" : ":ugeek:",
     "emotion" : "Uber Geek",
     "smiley_url" : "icon_e_ugeek.gif",
     "smiley_width" : 17,
     "smiley_height" : 18,
     "display_on_posting" : 1},
])

GROUPS = [
    {'group_id': '1',
     'group_name': 'GUESTS',
     'group_legend': '0',
     'group_max_recipients': '5',
     'group_founder_manage': '0',
     'group_colour': '',
     'group_type': '3'},
    {'group_id': '2',
     'group_name': 'REGISTERED',
     'group_legend': '0',
     'group_max_recipients': '5',
     'group_founder_manage': '0',
     'group_colour': '',
     'group_type': '3'},
    {'group_id': '3',
     'group_name': 'REGISTERED_COPPA',
     'group_legend': '0',
     'group_max_recipients': '5',
     'group_founder_manage': '0',
     'group_colour': '',
     'group_type': '3'},
    {'group_id': '4',
     'group_name': 'GLOBAL_MODERATORS',
     'group_legend': '1',
     'group_max_recipients': '0',
     'group_founder_manage': '0',
     'group_colour': '00AA00',
     'group_type': '3'},
    {'group_id': '5',
     'group_name': 'ADMINISTRATORS',
     'group_legend': '1',
     'group_max_recipients': '0',
     'group_founder_manage': '1',
     'group_colour': 'AA0000',
     'group_type': '3'},
    {'group_id': '6',
     'group_name': 'BOTS',
     'group_legend': '0',
     'group_max_recipients': '5',
     'group_founder_manage': '0',
     'group_colour': '9E8DA7',
     'group_type': '3'},
    {'group_id': '7',
     'group_name': 'NEWLY_REGISTERED', 
     'group_legend': '0',
     'group_max_recipients': '5',
     'group_founder_manage': '0',
     'group_colour': '',
     'group_type': '3'}
]
